import { useState, useCallback, useEffect } from 'react'
import { GitPullRequest, GitBranch, AlertCircle, ExternalLink, GitFork } from 'lucide-react'
import { Modal, Button, Input } from '../common'
import { useSettings } from '../../context/SettingsContext'
import { useToast } from '../../context/ToastContext'
import { githubApi } from '../../api/github'

interface PRCreationDialogProps {
  isOpen: boolean
  onClose: () => void
  repository?: { owner: string; name: string; branch: string }
  yaml: string
  onSuccess?: (prUrl: string) => void
}

// Generate unique branch name with timestamp
function generateBranchName(): string {
  const timestamp = Date.now()
  return `migrate-to-github-actions-${timestamp}`
}

export function PRCreationDialog({
  isOpen,
  onClose,
  repository,
  yaml,
  onSuccess,
}: PRCreationDialogProps) {
  const { settings } = useSettings()
  const toast = useToast()

  const [branchName, setBranchName] = useState(generateBranchName)
  const [commitMessage, setCommitMessage] = useState('chore: migrate CI/CD to GitHub Actions')
  const [prTitle, setPrTitle] = useState('Migrate CI/CD configuration to GitHub Actions')
  const [prBody, setPrBody] = useState(
    `## Summary
This PR migrates the CI/CD configuration to GitHub Actions.

## Changes
- Added \`.github/workflows/ci.yml\` with the migrated workflow

## Generated by
[CIPilot](https://github.com) - AI-powered CI/CD migration tool`
  )
  const [isCreating, setIsCreating] = useState(false)
  const [createdPrUrl, setCreatedPrUrl] = useState<string | null>(null)
  const [hasPushAccess, setHasPushAccess] = useState<boolean | null>(null)
  const [isCheckingAccess, setIsCheckingAccess] = useState(false)
  const [repoAccessError, setRepoAccessError] = useState<string | null>(null)

  // Reset branch name when dialog opens
  useEffect(() => {
    if (isOpen) {
      setBranchName(generateBranchName())
      setCreatedPrUrl(null)
      setRepoAccessError(null)
    }
  }, [isOpen])

  // Check push access when dialog opens
  useEffect(() => {
    if (isOpen && repository && settings.githubToken && hasPushAccess === null) {
      setIsCheckingAccess(true)

      // First verify we can access the repo at all
      githubApi
        .getRepo(settings.githubToken, repository.owner, repository.name)
        .then((repoData) => {
          console.log('[PR] Repository data:', {
            name: repoData.name,
            permissions: repoData.permissions,
            default_branch: repoData.default_branch
          })
          const hasAccess = repoData.permissions?.push || false
          console.log('[PR] Has push access:', hasAccess)
          setHasPushAccess(hasAccess)
          if (!hasAccess) {
            toast.info(
              'Fork required',
              "You don't have push access. We'll create a fork for your PR."
            )
          }
        })
        .catch((error: any) => {
          console.error('Access check error:', error)
          if (error.response?.status === 404) {
            setRepoAccessError('Repository not accessible. Please ensure your GitHub token has the "repo" scope.')
            toast.error(
              'Repository not accessible',
              'Please ensure your GitHub token has the "repo" scope and has access to this repository.'
            )
          } else if (error.response?.status === 401) {
            setRepoAccessError('Authentication failed. Your GitHub token may be invalid or expired.')
            toast.error(
              'Authentication failed',
              'Your GitHub token may be invalid or expired. Please check your settings.'
            )
          } else {
            setRepoAccessError('Failed to access repository. Please check your token permissions.')
          }
          setHasPushAccess(false)
        })
        .finally(() => {
          setIsCheckingAccess(false)
        })
    }
  }, [isOpen, repository, settings.githubToken, hasPushAccess, toast])

  // Reset access check when repository changes
  useEffect(() => {
    setHasPushAccess(null)
    setRepoAccessError(null)
  }, [repository?.owner, repository?.name])

  const handleCreate = useCallback(async () => {
    if (!repository || !settings.githubToken) return

    setIsCreating(true)
    try {
      const token = settings.githubToken
      let targetOwner = repository.owner
      let targetRepo = repository.name
      let actualBranchName = branchName // Track the actual branch name we use

      // If user doesn't have push access, fork the repo first
      if (hasPushAccess === false) {
        toast.info('Creating fork...', 'This may take a moment')
        try {
          const fork = await githubApi.forkRepo(token, repository.owner, repository.name)
          targetOwner = fork.owner.login
          targetRepo = fork.name

          // Wait a bit for the fork to be ready
          await new Promise((resolve) => setTimeout(resolve, 2000))
          toast.info('Fork created', `Working with ${targetOwner}/${targetRepo}`)
        } catch (forkError: any) {
          // Fork might already exist
          if (forkError.response?.status === 422) {
            // Get the current user to determine fork owner
            const user = await githubApi.getUser(token)
            targetOwner = user.login
            toast.info('Using existing fork', `${targetOwner}/${targetRepo}`)
          } else {
            throw forkError
          }
        }
      }

      // 1. Get default branch ref from the TARGET repo (fork or original)
      console.log(`[PR] Getting default branch ref from ${targetOwner}/${targetRepo}`)
      const { sha: baseSha, ref: baseRef } = await githubApi.getDefaultBranchRef(
        token,
        targetOwner,
        targetRepo
      )
      console.log(`[PR] Default branch: ${baseRef}, SHA: ${baseSha}`)

      // 2. Create a new branch FIRST (Chrome extension approach)
      let branchCreated = false
      let retries = 0
      const maxRetries = 3

      while (!branchCreated && retries < maxRetries) {
        try {
          console.log(`[PR] Creating branch ${actualBranchName} from base SHA ${baseSha}`)
          await githubApi.createBranch(token, {
            owner: targetOwner,
            repo: targetRepo,
            branchName: actualBranchName,
            baseSha: baseSha, // Point to the default branch's commit
          })
          branchCreated = true
          console.log(`[PR] Branch created successfully: ${actualBranchName}`)
        } catch (error: any) {
          console.error(`[PR] Branch creation error:`, error.response?.status, error.response?.data)
          if (error.response?.status === 422) {
            // Branch already exists - generate new name and retry
            retries++
            if (retries < maxRetries) {
              actualBranchName = generateBranchName()
              setBranchName(actualBranchName)
              console.log(`[PR] Branch exists, retrying with: ${actualBranchName}`)
              await new Promise(resolve => setTimeout(resolve, 500))
            } else {
              throw new Error('Could not create branch after multiple attempts. Try again later.')
            }
          } else {
            throw error
          }
        }
      }

      // 3. Use upsertFile to commit the workflow file (matching Chrome extension - no delay)
      console.log(`[PR] Committing workflow file to branch ${actualBranchName}...`)
      await githubApi.upsertFile(token, {
        owner: targetOwner,
        repo: targetRepo,
        path: '.github/workflows/ci.yml',
        content: yaml,
        branch: actualBranchName,
        message: commitMessage,
      })
      console.log(`[PR] Workflow file committed successfully`)

      // 4. Create pull request
      // For forks: PR from fork:branch to original:base
      // For direct: PR from branch to base
      const headRef = hasPushAccess === false ? `${targetOwner}:${actualBranchName}` : actualBranchName

      const pr = await githubApi.createPullRequest(token, {
        owner: repository.owner, // Always create PR on original repo
        repo: repository.name,
        title: prTitle,
        body: prBody,
        head: headRef,
        base: baseRef,
      })

      setCreatedPrUrl(pr.html_url)
      toast.success('Pull request created!', `PR #${pr.number} is ready for review`)
      onSuccess?.(pr.html_url)
    } catch (error: any) {
      console.error('PR creation error:', error)
      let message = error.response?.data?.message || error.message || 'Failed to create PR'

      // Provide more helpful error messages
      if (error.response?.status === 404) {
        message = 'Repository not found. Please check that the repository exists and your token has the correct permissions.'
      } else if (error.response?.status === 403) {
        message = 'Access denied. Please check that your GitHub token has the "repo" scope.'
      } else if (error.response?.status === 422) {
        message = error.response?.data?.message || 'Validation failed. The PR may already exist or there may be a conflict.'
      }

      toast.error('Failed to create PR', message)
    } finally {
      setIsCreating(false)
    }
  }, [repository, settings.githubToken, hasPushAccess, branchName, commitMessage, prTitle, prBody, yaml, toast, onSuccess])

  if (!repository) return null

  // Success state
  if (createdPrUrl) {
    return (
      <Modal
        isOpen={isOpen}
        onClose={onClose}
        title="Pull Request Created"
        size="md"
        footer={
          <>
            <Button variant="secondary" onClick={onClose}>
              Close
            </Button>
            <a href={createdPrUrl} target="_blank" rel="noopener noreferrer">
              <Button variant="primary" leftIcon={<ExternalLink className="w-4 h-4" />}>
                View Pull Request
              </Button>
            </a>
          </>
        }
      >
        <div className="text-center py-6">
          <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-green-100 dark:bg-green-900/30 flex items-center justify-center">
            <GitPullRequest className="w-8 h-8 text-green-500" />
          </div>
          <h3 className="text-lg font-semibold text-[var(--text-primary)] mb-2">Success!</h3>
          <p className="text-sm text-[var(--text-secondary)]">
            Your pull request has been created and is ready for review.
          </p>
        </div>
      </Modal>
    )
  }

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Create Pull Request"
      description={`Create a PR in ${repository.owner}/${repository.name}`}
      size="lg"
      footer={
        <>
          <Button variant="secondary" onClick={onClose} disabled={isCreating}>
            Cancel
          </Button>
          <Button
            variant="primary"
            onClick={handleCreate}
            isLoading={isCreating || isCheckingAccess}
            disabled={!branchName || !commitMessage || !prTitle || isCheckingAccess || !settings.githubToken || !!repoAccessError}
            leftIcon={hasPushAccess === false && !repoAccessError ? <GitFork className="w-4 h-4" /> : <GitPullRequest className="w-4 h-4" />}
          >
            {isCheckingAccess
              ? 'Checking access...'
              : repoAccessError
                ? 'Cannot Create PR'
                : hasPushAccess === false
                  ? 'Fork & Create PR'
                  : 'Create Pull Request'}
          </Button>
        </>
      }
    >
      <div className="space-y-4">
        {!settings.githubToken && (
          <div className="flex gap-3 p-3 rounded-lg bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800">
            <AlertCircle className="w-5 h-5 text-yellow-500 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-medium text-yellow-800 dark:text-yellow-300">
                GitHub Token Required
              </p>
              <p className="text-xs text-yellow-600 dark:text-yellow-400 mt-1">
                Add your GitHub Personal Access Token in Settings to create pull requests.
              </p>
            </div>
          </div>
        )}

        {/* Fork notice - shown when user doesn't have push access */}
        {settings.githubToken && hasPushAccess === false && (
          <div className="flex gap-3 p-3 rounded-lg bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800">
            <GitFork className="w-5 h-5 text-blue-500 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-medium text-blue-800 dark:text-blue-300">
                Fork Required
              </p>
              <p className="text-xs text-blue-600 dark:text-blue-400 mt-1">
                You don't have push access to this repository. A fork will be created automatically.
              </p>
            </div>
          </div>
        )}

        {/* Checking access loading state */}
        {isCheckingAccess && (
          <div className="flex items-center gap-2 p-3 rounded-lg bg-gray-50 dark:bg-gray-800/50 border border-gray-200 dark:border-gray-700">
            <div className="w-4 h-4 border-2 border-gray-300 dark:border-gray-600 border-t-primary-500 rounded-full animate-spin" />
            <span className="text-sm text-[var(--text-secondary)]">Checking repository access...</span>
          </div>
        )}

        {/* Repository access error */}
        {repoAccessError && (
          <div className="flex gap-3 p-3 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800">
            <AlertCircle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-medium text-red-800 dark:text-red-300">
                Cannot Create PR
              </p>
              <p className="text-xs text-red-600 dark:text-red-400 mt-1">
                {repoAccessError}
              </p>
              <p className="text-xs text-red-600 dark:text-red-400 mt-2">
                Your token needs the <code className="bg-red-100 dark:bg-red-900/50 px-1 rounded">repo</code> scope.
                You can update your token in Settings.
              </p>
            </div>
          </div>
        )}

        <Input
          label="Branch Name"
          value={branchName}
          onChange={(e) => setBranchName(e.target.value)}
          leftIcon={<GitBranch className="w-4 h-4" />}
        />

        <Input
          label="Commit Message"
          value={commitMessage}
          onChange={(e) => setCommitMessage(e.target.value)}
        />

        <Input
          label="PR Title"
          value={prTitle}
          onChange={(e) => setPrTitle(e.target.value)}
        />

        <div>
          <label className="block text-sm font-medium text-[var(--text-primary)] mb-2">
            PR Description
          </label>
          <textarea
            value={prBody}
            onChange={(e) => setPrBody(e.target.value)}
            rows={6}
            className="w-full px-4 py-3 rounded-xl bg-[var(--bg-glass)] border border-[var(--border)] text-[var(--text-primary)] placeholder:text-[var(--text-muted)] focus:outline-none focus:ring-2 focus:ring-primary-500/50 focus:border-primary-500 resize-none text-sm"
          />
        </div>
      </div>
    </Modal>
  )
}
