import { useState, useCallback, useEffect } from 'react'
import { GitPullRequest, GitBranch, AlertCircle, ExternalLink, GitFork, Server, User } from 'lucide-react'
import { Modal, Button, Input } from '../common'
import { useSettings } from '../../context/SettingsContext'
import { useToast } from '../../context/ToastContext'
import { githubProxyApi } from '../../api/githubProxy'

interface PRCreationDialogProps {
  isOpen: boolean
  onClose: () => void
  repository?: { owner: string; name: string; branch: string }
  yaml: string
  onSuccess?: (prUrl: string) => void
}

// Generate unique branch name with timestamp
function generateBranchName(): string {
  const timestamp = Date.now()
  return `migrate-to-github-actions-${timestamp}`
}

export function PRCreationDialog({
  isOpen,
  onClose,
  repository,
  yaml,
  onSuccess,
}: PRCreationDialogProps) {
  const { settings } = useSettings()
  const toast = useToast()

  const [branchName, setBranchName] = useState(generateBranchName)
  const [commitMessage, setCommitMessage] = useState('ci: add GitHub Actions workflow (migrated by CIPilot)')
  const [prTitle, setPrTitle] = useState('[CIPilot] Migrate CI/CD configuration to GitHub Actions')
  const [prBody, setPrBody] = useState(
    `## Summary

This pull request migrates the existing CI/CD configuration to GitHub Actions.

## Changes

- Added \`.github/workflows/ci.yml\` with the migrated workflow configuration
- The new workflow preserves the original pipeline's functionality while leveraging GitHub Actions' native integration with GitHub

## About This Migration

This migration was generated using [CIPilot](https://cipilot.com), an **experimental research tool** developed as part of academic research into automated CI/CD migration.

**How it works:** CIPilot uses an agentic AI system powered by Large Language Models (LLMs) to analyze your existing CI/CD configuration and convert it to an equivalent GitHub Actions workflow. The AI agents iteratively refine the output through automated syntax and schema validation, using feedback loops to improve accuracy.

> **Note:** This tool is currently experimental and part of ongoing research. While we strive for accuracy, please review the generated workflow carefully before merging.

## Validation

The generated workflow has been validated for:
- YAML syntax correctness
- GitHub Actions schema compliance

## Before You Merge

We recommend reviewing the generated workflow to ensure it fits your project's needs:
- Verify that environment variables and secrets are correctly referenced
- Test the workflow in a feature branch before merging
- Adjust any project-specific settings as needed

Learn more about this research project at [cipilot.com](https://cipilot.com).

---

*Generated by [CIPilot](https://cipilot.com) — Experimental Agentic AI for CI/CD migration*`
  )
  const [isCreating, setIsCreating] = useState(false)
  const [createdPrUrl, setCreatedPrUrl] = useState<string | null>(null)
  const [hasPushAccess, setHasPushAccess] = useState<boolean | null>(null)
  const [isCheckingAccess, setIsCheckingAccess] = useState(false)
  const [repoAccessError, setRepoAccessError] = useState<string | null>(null)
  const [serverTokenAvailable, setServerTokenAvailable] = useState<boolean | null>(null)

  // Determine which token to use: user's own token or server token (via proxy)
  const userToken = settings.githubToken || undefined
  const canCreatePR = serverTokenAvailable || !!userToken

  // Reset branch name when dialog opens
  useEffect(() => {
    if (isOpen) {
      setBranchName(generateBranchName())
      setCreatedPrUrl(null)
      setRepoAccessError(null)
    }
  }, [isOpen])

  // Check if server token is available (only once)
  useEffect(() => {
    if (serverTokenAvailable === null) {
      githubProxyApi.getStatus()
        .then((status) => {
          setServerTokenAvailable(status.server_token_configured)
          console.log('[PR] Server token available:', status.server_token_configured)
        })
        .catch(() => {
          setServerTokenAvailable(false)
        })
    }
  }, [serverTokenAvailable])

  // Check push access when dialog opens
  useEffect(() => {
    if (isOpen && repository && canCreatePR && hasPushAccess === null) {
      setIsCheckingAccess(true)

      // Use proxy API - it will use server token if no user token
      githubProxyApi
        .checkAccess(repository.owner, repository.name, userToken)
        .then((result) => {
          if (!result.success) {
            console.error('[PR] Access check failed:', result.error)
            setRepoAccessError(result.error || 'Failed to check repository access')
            setHasPushAccess(false)
            return
          }
          
          console.log('[PR] Access check result:', result.data)
          const hasAccess = result.data?.has_push_access || false
          setHasPushAccess(hasAccess)
          
          if (!hasAccess) {
            toast.info(
              'Fork required',
              "You don't have push access. We'll create a fork for your PR."
            )
          }
        })
        .catch((error: Error) => {
          console.error('Access check error:', error)
          setRepoAccessError('Failed to access repository. Please try again.')
          setHasPushAccess(false)
        })
        .finally(() => {
          setIsCheckingAccess(false)
        })
    }
  }, [isOpen, repository, canCreatePR, userToken, hasPushAccess, toast])

  // Reset access check when repository changes
  useEffect(() => {
    setHasPushAccess(null)
    setRepoAccessError(null)
  }, [repository?.owner, repository?.name])

  const handleCreate = useCallback(async () => {
    if (!repository || !canCreatePR) return

    setIsCreating(true)
    try {
      let targetOwner = repository.owner
      let targetRepo = repository.name
      let actualBranchName = branchName

      // If user doesn't have push access, fork the repo first
      if (hasPushAccess === false) {
        toast.info('Creating fork...', 'This may take a moment')
        
        const forkResult = await githubProxyApi.forkRepo(
          repository.owner, 
          repository.name,
          userToken
        )
        
        if (!forkResult.success || !forkResult.data) {
          throw new Error(forkResult.error || 'Failed to fork repository')
        }
        
        targetOwner = forkResult.data.owner
        targetRepo = forkResult.data.repo

        // Wait a bit for the fork to be ready
        await new Promise((resolve) => setTimeout(resolve, 2000))
        
        if (forkResult.data.already_exists) {
          toast.info('Using existing fork', `${targetOwner}/${targetRepo}`)
        } else {
          toast.info('Fork created', `${targetOwner}/${targetRepo}`)
        }
      }

      // 1. Get default branch ref from the TARGET repo (fork or original)
      console.log(`[PR] Getting default branch ref from ${targetOwner}/${targetRepo}`)
      const branchRefResult = await githubProxyApi.getDefaultBranchRef(
        targetOwner,
        targetRepo,
        userToken
      )
      
      if (!branchRefResult.success || !branchRefResult.data) {
        throw new Error(branchRefResult.error || 'Failed to get default branch')
      }
      
      const baseSha = branchRefResult.data.sha
      const baseRef = branchRefResult.data.ref
      console.log(`[PR] Default branch: ${baseRef}, SHA: ${baseSha}`)

      // 2. Create a new branch
      let branchCreated = false
      let retries = 0
      const maxRetries = 3

      while (!branchCreated && retries < maxRetries) {
        console.log(`[PR] Creating branch ${actualBranchName} from base SHA ${baseSha}`)
        
        const branchResult = await githubProxyApi.createBranch(
          targetOwner,
          targetRepo,
          actualBranchName,
          baseSha,
          userToken
        )
        
        if (branchResult.success) {
          branchCreated = true
          console.log(`[PR] Branch created successfully: ${actualBranchName}`)
        } else if (branchResult.error?.includes('already exists')) {
          // Branch already exists - generate new name and retry
          retries++
          if (retries < maxRetries) {
            actualBranchName = generateBranchName()
            setBranchName(actualBranchName)
            console.log(`[PR] Branch exists, retrying with: ${actualBranchName}`)
            await new Promise(resolve => setTimeout(resolve, 500))
          } else {
            throw new Error('Could not create branch after multiple attempts. Try again later.')
          }
        } else {
          throw new Error(branchResult.error || 'Failed to create branch')
        }
      }

      // 3. Commit the workflow file
      console.log(`[PR] Committing workflow file to branch ${actualBranchName}...`)
      
      const commitResult = await githubProxyApi.commitFile({
        owner: targetOwner,
        repo: targetRepo,
        path: '.github/workflows/ci.yml',
        content: yaml,
        branch: actualBranchName,
        message: commitMessage,
      }, userToken)
      
      if (!commitResult.success) {
        throw new Error(commitResult.error || 'Failed to commit workflow file')
      }
      console.log(`[PR] Workflow file committed successfully`)

      // 4. Create pull request
      // For forks: PR from fork:branch to original:base
      // For direct: PR from branch to base
      const headRef = hasPushAccess === false ? `${targetOwner}:${actualBranchName}` : actualBranchName

      const prResult = await githubProxyApi.createPullRequest({
        owner: repository.owner, // Always create PR on original repo
        repo: repository.name,
        title: prTitle,
        body: prBody,
        head: headRef,
        base: baseRef,
      }, userToken)
      
      if (!prResult.success || !prResult.data) {
        throw new Error(prResult.error || 'Failed to create pull request')
      }

      setCreatedPrUrl(prResult.data.html_url)
      toast.success('Pull request created!', `PR #${prResult.data.number} is ready for review`)
      onSuccess?.(prResult.data.html_url)
    } catch (error: unknown) {
      console.error('PR creation error:', error)
      const message = error instanceof Error ? error.message : 'Failed to create PR'
      toast.error('Failed to create PR', message)
    } finally {
      setIsCreating(false)
    }
  }, [repository, canCreatePR, userToken, hasPushAccess, branchName, commitMessage, prTitle, prBody, yaml, toast, onSuccess])

  if (!repository) return null

  // Success state
  if (createdPrUrl) {
    return (
      <Modal
        isOpen={isOpen}
        onClose={onClose}
        title="Pull Request Created"
        size="md"
        footer={
          <>
            <Button variant="secondary" onClick={onClose}>
              Close
            </Button>
            <a href={createdPrUrl} target="_blank" rel="noopener noreferrer">
              <Button variant="primary" leftIcon={<ExternalLink className="w-4 h-4" />}>
                View Pull Request
              </Button>
            </a>
          </>
        }
      >
        <div className="text-center py-6">
          <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-green-100 dark:bg-green-900/30 flex items-center justify-center">
            <GitPullRequest className="w-8 h-8 text-green-500" />
          </div>
          <h3 className="text-lg font-semibold text-[var(--text-primary)] mb-2">Success!</h3>
          <p className="text-sm text-[var(--text-secondary)]">
            Your pull request has been created and is ready for review.
          </p>
        </div>
      </Modal>
    )
  }

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Create Pull Request"
      description={`Create a PR in ${repository.owner}/${repository.name}`}
      size="lg"
      footer={
        <>
          <Button variant="secondary" onClick={onClose} disabled={isCreating}>
            Cancel
          </Button>
          <Button
            variant="primary"
            onClick={handleCreate}
            isLoading={isCreating || isCheckingAccess}
            disabled={!branchName || !commitMessage || !prTitle || isCheckingAccess || !canCreatePR || !!repoAccessError}
            leftIcon={hasPushAccess === false && !repoAccessError ? <GitFork className="w-4 h-4" /> : <GitPullRequest className="w-4 h-4" />}
          >
            {isCheckingAccess
              ? 'Checking access...'
              : repoAccessError
                ? 'Cannot Create PR'
                : hasPushAccess === false
                  ? 'Fork & Create PR'
                  : 'Create Pull Request'}
          </Button>
        </>
      }
    >
      <div className="space-y-4">
        {/* Token status indicator */}
        {canCreatePR && (
          <div className={`flex gap-3 p-3 rounded-lg ${
            userToken 
              ? 'bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800'
              : 'bg-purple-50 dark:bg-purple-900/20 border border-purple-200 dark:border-purple-800'
          }`}>
            {userToken ? (
              <User className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
            ) : (
              <Server className="w-5 h-5 text-purple-500 flex-shrink-0 mt-0.5" />
            )}
            <div>
              <p className={`text-sm font-medium ${
                userToken 
                  ? 'text-green-800 dark:text-green-300'
                  : 'text-purple-800 dark:text-purple-300'
              }`}>
                {userToken ? 'Using Your GitHub Account' : 'Using CIPilot Account'}
              </p>
              <p className={`text-xs mt-1 ${
                userToken 
                  ? 'text-green-600 dark:text-green-400'
                  : 'text-purple-600 dark:text-purple-400'
              }`}>
                {userToken 
                  ? 'The PR will be created using your personal GitHub token.'
                  : 'The PR will be created via CIPilot\'s GitHub account. You can add your own token in Settings to use your account.'
                }
              </p>
            </div>
          </div>
        )}

        {/* No token available - show error only if server token is also unavailable */}
        {!canCreatePR && serverTokenAvailable !== null && (
          <div className="flex gap-3 p-3 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800">
            <AlertCircle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-medium text-red-800 dark:text-red-300">
                GitHub Connection Required
              </p>
              <p className="text-xs text-red-600 dark:text-red-400 mt-1">
                Server-side GitHub connection is not available. Please add your GitHub Personal Access Token in Settings to create pull requests.
              </p>
            </div>
          </div>
        )}

        {/* Fork notice - shown when user doesn't have push access */}
        {canCreatePR && hasPushAccess === false && !repoAccessError && (
          <div className="flex gap-3 p-3 rounded-lg bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800">
            <GitFork className="w-5 h-5 text-blue-500 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-medium text-blue-800 dark:text-blue-300">
                Fork Required
              </p>
              <p className="text-xs text-blue-600 dark:text-blue-400 mt-1">
                You don't have push access to this repository. A fork will be created automatically.
              </p>
            </div>
          </div>
        )}

        {/* Checking access loading state */}
        {isCheckingAccess && (
          <div className="flex items-center gap-2 p-3 rounded-lg bg-gray-50 dark:bg-gray-800/50 border border-gray-200 dark:border-gray-700">
            <div className="w-4 h-4 border-2 border-gray-300 dark:border-gray-600 border-t-primary-500 rounded-full animate-spin" />
            <span className="text-sm text-[var(--text-secondary)]">Checking repository access...</span>
          </div>
        )}

        {/* Repository access error */}
        {repoAccessError && (
          <div className="flex gap-3 p-3 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800">
            <AlertCircle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
            <div>
              <p className="text-sm font-medium text-red-800 dark:text-red-300">
                Cannot Create PR
              </p>
              <p className="text-xs text-red-600 dark:text-red-400 mt-1">
                {repoAccessError}
              </p>
              <p className="text-xs text-red-600 dark:text-red-400 mt-2">
                Your token needs the <code className="bg-red-100 dark:bg-red-900/50 px-1 rounded">repo</code> scope.
                You can update your token in Settings.
              </p>
            </div>
          </div>
        )}

        <Input
          label="Branch Name"
          value={branchName}
          onChange={(e) => setBranchName(e.target.value)}
          leftIcon={<GitBranch className="w-4 h-4" />}
        />

        <Input
          label="Commit Message"
          value={commitMessage}
          onChange={(e) => setCommitMessage(e.target.value)}
        />

        <Input
          label="PR Title"
          value={prTitle}
          onChange={(e) => setPrTitle(e.target.value)}
        />

        <div>
          <label className="block text-sm font-medium text-[var(--text-primary)] mb-2">
            PR Description
          </label>
          <textarea
            value={prBody}
            onChange={(e) => setPrBody(e.target.value)}
            rows={6}
            className="w-full px-4 py-3 rounded-xl bg-[var(--bg-glass)] border border-[var(--border)] text-[var(--text-primary)] placeholder:text-[var(--text-muted)] focus:outline-none focus:ring-2 focus:ring-primary-500/50 focus:border-primary-500 resize-none text-sm"
          />
        </div>
      </div>
    </Modal>
  )
}
